config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"
  get "/following" => "pages#following"

  # Session Routes -------------------------------------------
  # Login Form
  get "/login" => "session#new"
  # Login Form submits here, do authentication & create session
  post "/login" => "session#create"
  # Logout, delete session
  delete "/login" => "session#destroy"
  
  # USER CRUD -------------------------------------------
  resources :users do
    # Nested routes get user id in URL
    resources :follows 
  end

  # POST CRUD -------------------------------------------
  resources :posts do
    # Nested routes get post id in URL
    resources :likes
    resources :saves
  end

  # COMMENT CRUD ----------------------------------------
  resources :comments

end

app/views/pages/following.html.erb
<div class="post_list_wrapper">
  <ul>
    <% @posts.each do |post| %>
      <!-- Only show posts that @current_user following -->
      <% if @current_user.following.include? post.user %>
      <div class="post_list_item">
      <li>
        
        <!-- post list header -->
        <div class="post_item_header">
          <!-- Adding comment anchoring point, back to this position after comment, like, save -->
          <a name="<%= post.id %>"></a>
          <div class="post_item_header_left">
            <!-- helpers check_user_image exists -->
            <%= check_user_image_small(post.user) %>
          </div>
          <div class="post_item_header_middle">
            <strong><%= link_to post.user.name, user_path(post.user_id) %></strong>
          </div>
          <div class="post_item_header_right">
            <!-- post.created date -->
            <%= post.created_at.strftime("%e %b") %><br>
          </div>
        </div>

        <!-- post.image & description -->
        <div class="post_item_image">
          <%= link_to cl_image_tag(post.image, alt: post.description, class: "post_image"), post_path(post.id) %><br>
          <div class="brand_tag">
            <%= post.brand %>
          </div>
        </div>

        <!-- post interaction -->
        <div class="post_item_interaction">
          <!-- like -->
          <div class="post_item_interaction_left">
            <!-- If user has liked this post -->
            <% pre_liked = Like.where(user_id: @current_user.id, post_id: post.id) %>
            <% if pre_liked.exists? %>
              <%= link_to image_tag("icon_unlike.svg", alt: "Unlike"), post_like_path(post.id, pre_liked.first.id), method: "delete"  %>
            <% else %>
              <%= link_to image_tag("icon_like.svg", alt: "Like"), post_likes_path(post.id), method: "post" %>
            <% end %>
          </div>
          <div class="post_item_interaction_middle">
            <%= post.likes.count %><%= (post.likes.count) <= 1 ? " Like" : " Likes" %><br>
          </div>
          <!-- save -->
          <div class="post_item_interaction_right">
            <% if @current_user.saved_posts.include? post %>
              <%= link_to image_tag("icon_saved.svg", alt: "Unlike"), post_safe_path(post.id, @current_user.id), method: "delete" %>
            <% else %>
              <%= link_to image_tag("icon_save.svg", alt: "Unlike"), post_saves_path(post.id), method: "post" %>
            <% end %>
          </div>
        </div>

        <!-- description -->
        <div class="post_item_description">
          <strong><%= link_to post.user.name, user_path(post.user.id) %></strong>
          <%= post.description %><br>
        </div>

        <!-- post.comments.link -->
        <div class="post_item_comment_link">
        <% if post.comments.count >= 1 %>
          <%= link_to "View all #{post.comments.count} comments", post_path(post.id) %><br>
        <% end %>
        </div>
        <div class="post_item_comment_list">
          <% if post.comments.first.present? %>
            <strong><%= post.comments.first.user.name %></strong>
            <%= post.comments.first.content %><br>
          <% end %>
          <% if post.comments.last.present? && post.comments.count > 1 %>
            <strong><%= post.comments.last.user.name %></strong>
            <%= post.comments.last.content %>
          <% end %>
        </div>

        <!-- Comment Field -->
        <div class="post_item_comment">
          <%= form_for @comment do |f| %>
            <%= f.hidden_field :post_id, value: post.id %>
            <%= f.text_field :content, class: "post_list_input post_item_comment_item" %>
            <%= f.submit "Comment", class: "post_list_button post_item_comment_item"  %>
          <% end %>
        </div>
        <div class="error_message">
        <% if flash[:error] && post.id == flash[:error][1] %>
          <strong><%= flash[:error][0] %></strong>
        <% end %>
        </div>
      </li>
      </div>
      <% end %>
    <% end %>
  </ul>
</div>