config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"
  get "/following" => "pages#following"

  # Session Routes -------------------------------------------
  # Login Form
  get "/login" => "session#new"
  # Login Form submits here, do authentication & create session
  post "/login" => "session#create"
  # Logout, delete session
  delete "/login" => "session#destroy"
  
  # USER CRUD -------------------------------------------
  resources :users do
    # Nested routes get user id in URL
    resources :follows 
  end

  # POST CRUD -------------------------------------------
  resources :posts do
    # Nested routes get post id in URL
    resources :likes
    resources :saves
  end

  # COMMENT CRUD ----------------------------------------
  resources :comments

end

app/models/post.rb
class Post < ApplicationRecord
  # User association
  belongs_to :user, optional: true
  # Comments association
  has_many :comments
  # Like association
  has_many :likes, dependent: :destroy
  # Save association
  has_and_belongs_to_many :saved_by_users, class_name: "User"
  validates :image, presence: true, on: :create
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :check_if_logged_in

  # CREATE -------------------------------------------
  def new
    @post = Post.new
  end # new

  def create
    @post = Post.create post_params
    # Check if there is uploaded image
    if params[:file].present?
      # Actually forward upload file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @post.image = response['public_id']
      @post.save
      @current_user.posts << @post
      redirect_to(posts_path)
    else 
      render :new
    end
  end # create

  # READ -------------------------------------------
  def index
    # DESC: show descending latest to oldest
    @posts = Post.all.order("created_at DESC")
    # Create comment on index page
    @comment = Comment.new
  end # index

  def show
    @post = Post.find params[:id]
    # Create comment on show page
    @comment = Comment.new
  end # show
  
  # UPDATE -------------------------------------------
  def edit
    @post = Post.find params[:id]
    # Check if @current_user is the @post.user
    if @post.user_id != @current_user.id
      redirect_to(posts_path)
    end
  end # edit

  def update
    @post = Post.find params[:id]
    # Check if @current_user is the @post.user
    if @post.user_id != @current_user.id
      redirect_to(posts_path)
      return
    end
    # Check if there is uploaded image
    if params[:file].present?
      # Actually forward upload file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @post.image = response['public_id']
      @post.save
      @post.update post_params
      redirect_to(post_path(params[:id]))
    else
      # Save error message and send to template
      flash[:error] = "Image can't be blank."
      redirect_to(edit_post_path(params[:id]))
    end
  end # update

  # DESTROY -------------------------------------------
  def destroy
    Post.destroy params[:id]
    redirect_to(posts_path)
  end # destroy


  private

  def post_params
    params.require(:post).permit(:image, :description, :brand)
  end # post_params

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="form">
  <%= form_for @post, html: {multipart: true} do |f| %>
    <%= f.label :image, "Upload image" %>
    <%= f.cl_image_upload :image %>
    <%= f.label :description, "Add description" %>
    <%= f.text_area :description, rows: "7" %>
    <%= f.label :brand, "Select brand" %>
    <%= f.select :brand, [["Li-Ning", "Li-Ning"], ["Air Jordan", "Air Jordan"], ["Nike","Nike"], ["Adidas", "Adidas"], ["Reebok", "Reebod"], ["Converse", "Converse"], ["Others", "Others"]] %>
    <%= f.submit nil, class: "button_submit" %>
  <% end %>
  <!-- post create error message -->
  <div class="error_message">
    <% if @post.errors.full_messages.any? %>
      <ul>
        <% @post.errors.full_messages.each do |error| %>
          <li><strong><%= error %></strong></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <!-- post update error message -->
  <div class="error_message">
    <% if flash[:error] %>
      <strong><%= flash[:error] %></strong>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="center_wrapper">
  <p class="back_button"><%= link_to 'Back', :back %></p>
  <h1>Edit Your Post</h1>
  <!-- form -->
  <%= render partial: "form" %>
</div>

app/views/posts/index.html.erb
<div class="post_list_wrapper">

  <ul>
    <% @posts.each do |post| %>
      <div class="post_list_item">
      <li>
        <!-- post list header -->
        <div class="post_item_header">
          <!-- Adding comment anchoring point -->
          <a name="<%= post.id %>"></a>
          <div class="post_item_header_left">
            <!-- helpers check_user_image -->
            <%= check_user_image_small(post.user) %>
            <!-- post.user.name -->
          </div>
          <div class="post_item_header_middle">
            <strong><%= link_to post.user.name, user_path(post.user_id) %></strong>
          </div>
          <div class="post_item_header_right">
            <!-- post.created date -->
            <%= post.created_at.strftime("%e %b") %><br>
          </div>
        </div>

        <!-- post.image & description -->
        <div class="post_item_image">
          <%= link_to cl_image_tag(post.image, alt: post.description, class: "post_image"), post_path(post.id) %><br>
          <div class="brand_tag">
            <%= post.brand %>
          </div>
        </div>

        <!-- like -->
        <div class="post_item_interaction">
          <div class="post_item_interaction_left">
            <!-- If user has liked this post -->
            <% pre_liked = Like.where(user_id: @current_user.id, post_id: post.id) %>
            <% if Like.where(user_id: @current_user.id, post_id: post.id).exists? %>
              <%= link_to image_tag("icon_unlike.svg", alt: "Unlike"), post_like_path(post.id, pre_liked.first.id), method: "delete"  %>
            <% else %>
              <%= link_to image_tag("icon_like.svg", alt: "Like"), post_likes_path(post.id), method: "post" %>
            <% end %>
          </div>
          <div class="post_item_interaction_middle">
            <%= post.likes.count %><%= (post.likes.count) <= 1 ? " Like" : " Likes" %><br>
          </div>
          <!-- save -->
          <div class="post_item_interaction_right">
            <% if @current_user.saved_posts.include? post %>
              <%= link_to image_tag("icon_saved.svg", alt: "Unlike"), post_safe_path(post.id, @current_user.id), method: "delete" %>
            <% else %>
              <%= link_to image_tag("icon_save.svg", alt: "Unlike"), post_saves_path(post.id), method: "post" %>
            <% end %>
          </div>
        </div>

        <!-- description -->
        <div class="post_item_description">
          <strong><%= link_to post.user.name, user_path(post.user.id) %></strong>
          <%= post.description %><br>
        </div>

        <!-- post.comments.link -->
        <div class="post_item_comment_link">
        <% if post.comments.count >= 1 %>
          <%= link_to "View all #{post.comments.count} comments", post_path(post.id) %><br>
        <% end %>
        </div>
        <div class="post_item_comment_list">
          <% if post.comments.first.present? %>
            <strong><%= post.comments.first.user.name %></strong>
            <%= post.comments.first.content %><br>
          <% end %>
          <% if post.comments.last.present? && post.comments.count > 1 %>
            <strong><%= post.comments.last.user.name %></strong>
            <%= post.comments.last.content %>
          <% end %>
        </div>

        <!-- Comment Field -->
        <div class="post_item_comment">
          <%= form_for @comment do |f| %>
            <%= f.hidden_field :post_id, value: post.id %>
            <%= f.text_field :content, class: "post_list_input post_item_comment_item" %>
            <%= f.submit "Comment", class: "post_list_button post_item_comment_item"  %>
          <% end %>
        </div>
        <div class="error_message">
        <% if flash[:error] && post.id == flash[:error][1] %>
          <strong><%= flash[:error][0] %></strong>
        <% end %>
        </div>
      </li>
      </div>
    <% end %>

  </ul>
</div>

app/views/posts/new.html.erb
<div class="center_wrapper">
  <p class="back_button"><%= link_to 'Back', :back %></p>
  <h1>Create a Post</h1>
  <!-- form -->
  <%= render partial: "form" %>
</div>

app/views/posts/show.html.erb
<div class="center_wrapper post_show_wrapper">
  <!-- Adding comment anchoring point -->
  <a name="start"></a>
  <!-- Left Image -->
  <div class="post_show_left">
    <%= cl_image_tag @post.image, alt: @post.description, class: "post_image" %><br>
    <%= @post.created_at.strftime("%e %b %Y %l:%M %p") %>
    <div class="user_post_edit">
      <!-- If @current_user equals post user show "edit" & "delete" -->
      <% if @current_user.id == @post.user_id %>
        <%= link_to "Edit", edit_post_path(@post.id) %>
        |
        <%= link_to "Delete", post_path(@post.id), method: "delete" %>
      <% end %>
    </div>
  </div>

  <!-- Right content -->
  <div class="post_show_right">
    <div class="post_item_header post_show_header">
      <div class="post_item_header_left">
        <%= check_user_image_small(@post.user) %>
      </div>
      <div class="post_item_header_middle">
        <strong><%= link_to @post.user.name, user_path(@post.user_id) %></strong><br>
      </div>
      <!-- Show follow when it's not user himself -->
      <% if @current_user.id != @post.user_id %>
      <div class="post_item_header_right follow_button">
        <% pre_followed = Follow.where(follower_id: @current_user.id, followed_id: @post.user_id) %>
        <% if pre_followed.exists? %>
          <%= link_to "Unfollow", user_follow_path(@post.user_id, pre_followed.first.id), method: "delete" %>
        <% else %>
          <%= link_to "Follow", user_follows_path(@post.user_id), method: "post" %>
        <% end %>
      </div>
      <% end %>
      <div class="divider"> </div>
      <br>
    </div>

    <!-- like -->
    <div class="post_item_interaction">
      <div class="post_item_interaction_left">
        <% pre_liked = Like.where(user_id: @current_user.id, post_id: @post.id) %>
        <!-- If user has liked this post -->
        <% if pre_liked.exists? %>
          <%= link_to image_tag("icon_unlike.svg", alt: "Unlike", class: "like_unlike_icon"), post_like_path(@post.id, pre_liked.first.id), method: "delete"  %>
        <% else %>
          <%= link_to image_tag("icon_like.svg", alt: "Like", class: "like_unlike_icon"), post_likes_path(@post.id), method: "post" %>
        <% end %>
      </div>
      <div class="post_item_interaction_middle">
        <%= @post.likes.count %><%= (@post.likes.count) <= 1 ? " Like" : " Likes" %><br>
      </div>
      <!-- save -->
      <div class="post_item_interaction_right">
        <% if @current_user.saved_posts.include? @post %>
          <%= link_to image_tag("icon_saved.svg", alt: "Unlike"), post_safe_path(@post.id, @current_user.id), method: "delete" %>
        <% else %>
          <%= link_to image_tag("icon_save.svg", alt: "Unlike"), post_saves_path(@post.id), method: "post" %>
        <% end %>
      </div>
    </div>

    <div class="post_item_description">
      <strong><%= @post.user.name %></strong>
      <%= @post.description %>
    </div>

    <!-- Comments -->
    <div class="post_item_comment_list">
      <% @post.comments.order("created_at").each do |comment| %>
        <div class="post_item_comment_list_item">
          <strong><%= comment.user.name %></strong>
          <%= comment.content %><br>
          <div class="comment_edit">
            <div class="comment_date">
              <%= comment.created_at.strftime("%e %b %Y %l:%M %p") %>
            </div>
            <div class="comment_delete">
              <% if @current_user.id == comment.user_id %>
                <%= link_to "Delete", comment_path(comment.id), method: "delete" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <!-- Comment Field -->
    <div class="post_item_comment">
      <a name="end"></a>
      <%= form_for @comment do |f| %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <%= f.text_area :content %>
        <%= f.submit "Comment", class: "post_show_button" %>
      <% end %>
      <div class="error_message">
      <% if flash[:error] %>
        <strong><%= flash[:error] %></strong>
      <% end %>
      </div>
    </div>
  </div>
</div>