config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"
  get "/following" => "pages#following"

  # Session Routes -------------------------------------------
  # Login Form
  get "/login" => "session#new"
  # Login Form submits here, do authentication & create session
  post "/login" => "session#create"
  # Logout, delete session
  delete "/login" => "session#destroy"
  
  # USER CRUD -------------------------------------------
  resources :users do
    # Nested routes get user id in URL
    resources :follows 
  end

  # POST CRUD -------------------------------------------
  resources :posts do
    # Nested routes get post id in URL
    resources :likes
    resources :saves
  end

  # COMMENT CRUD ----------------------------------------
  resources :comments

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wdywt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <nav class="nav_main">
      <div class="nav_main_wrapper">
        <div class="nav_left">
          <%= link_to image_tag("logo.svg", alt: "WDYWT Logo", class: "logo"), root_path %>
        </div>
        <div class="nav_right">
          <!-- If user logged in -->
          <% if @current_user.present? %>
            <ul class="nav_menu">
              <li>Hello, <%= @current_user.name %></li>
              <% if @current_user.following.exists? %>
                <li><%= link_to "Following", following_path %></li>
              <% end %>
              <li><%= link_to "Profile", user_path(@current_user.id) %></li>
              <li><%= link_to "Logout", login_path, method: "delete" %></li>
              <li><%= link_to "Post", new_post_path, class: "post_button" %></li>
            </ul>
          <% else %>
          <!-- If user not logged in -->
            <ul class="nav_menu">
              <li><%= link_to "Login", login_path %></li>
              <li><%= link_to "Sign Up", new_user_path %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>

    <%= yield %>

    <footer>
      <div class="footer_wrapper">
        <div class="footer_left">
          <p>&copy 2020 Ryan Xin - General Assembly SEI 37.</p>
        </div>
        <div class="footer_right">
          <ul class="nav_menu">
            <li><p><%= link_to "LinkedIn", "https://www.linkedin.com/in/ryan-xin/", target: "_blank" %></p></li>
            <li><p><%= link_to "GitHub", "https://github.com/ryan-xin/wdywt", target: "_blank" %></p></li>
          </ul>
        </div>
      </div>
    </footer>
    
  </body>
</html>